---
## Ansible playbook for a CentOS 7 CIS Base
##
##
- hosts: localhost
  user: vagrant
  sudo: yes
  gather_facts: yes
  tasks:
    - include: 'tasks/section_01.yml'
    - include: 'tasks/section_02.yml'
    - include: 'tasks/section_03.yml'
    - include: 'tasks/section_04.yml'
    - include: 'tasks/section_05.yml'
    - include: 'tasks/cis_6-1.yml'
    - include: 'tasks/cis_6-2.yml'
