- name: CIS 1.6 Additional Process Hardening
  debug: msg="*** Starting CIS section 1.6"
- name: CIS 1.6.1 Restrict Core Dumps (PAM)
  lineinfile: >
    dest=/etc/security/limits.conf
    line="* hard core 0"
    insertafter=EOF
  tags:
    - cis-level-1
    - cis_1.6
    - cis_1.6.1
- name: CIS 1.6.1 Restrict core dumps (sysctl)
  sysctl: >
    name=fs.suid_dumpable
    value=0
    state=present
    ignoreerrors=yes
    sysctl_file=/etc/sysctl.conf
  tags:
    - cis-level-1
    - cis_1.6
    - cis_1.6.1
- name: CIS 1.6.2 Enable Randomized Virtual Memory Region Placement
  sysctl: >
    name=kernel.randomize_va_space
    value=2
    state=present
    ignoreerrors=yes
    sysctl_file=/etc/sysctl.conf
  tags:
    - cis-level-1
    - cis_1.6
    - cis_1.6.2
