- name: CIS 5.1 Configure rsyslog
  debug: msg="*** Starting CIS section 5.1"
  tags:
    - cis-level-1
    - cis_5
    - cis_5.1
- name: CIS 5.1.1 Install the rsyslog package
  yum: >
    name=rsyslog
    state=present
  tags:
    - cis-level-1
    - cis_5
    - cis_5.1
    - cis_5.1.1
- name: CIS 5.1.2 Activate the rsyslog Service
  service: >
    name=rsyslog
    state=started
    enabled=yes
  tags:
    - cis-level-1
    - cis_5
    - cis_5.1
    - cis_5.1.2
- name: CIS 5.1.3 Configure /etc/rsyslog.conf
  template: src=templates/rsyslog.conf.j2 dest=/etc/rsyslog.conf owner=root group=root mode=0644
  tags:
    - cis-level-1
    - cis_5
    - cis_5.1
    - cis_5.1.3
- name: CIS 5.1.4 Create and Set Permissions on rsyslog Log Files
  file: >
    path=/var/log/{{item}}
    state=touch
    owner=root
    group=wheel
    mode=0640
  with_items:
    - messages
    - kern.log
    - daemon.log
    - syslog
    - unused.log
    - firewalld
    - secure
    - maillog
  tags:
    - cis-level-1
    - cis_5
    - cis_5.1
    - cis_5.1.4
- name: CIS 5.1.5 Configure rsyslog to Send Logs to a Remote Log Host
  lineinfile: >
    dest=/etc/rsyslog.conf
    line="*.* @@{{syslog_server}}"
    insertafter=EOF
  when: syslog_server is defined
  tags:
    - cis-level-1
    - cis_5
    - cis_5.1
    - cis_5.1.5
- name: CIS 5.1.6 Accept Remote rsyslog Messages Only on Designated Log Hosts
  debug: msg="*** Not required central syslog server is out of scope of this role"
  tags:
    - cis-level-1
    - cis_5
    - cis_5.1
    - cis_5.1.6