## CIS 5.1 Configure rsyslog
# CIS 5.1.1 Install the rsyslog package
### - cis-level-1
yum install rsyslog

# CIS 5.1.2 Activate the rsyslog Service
### - cis-level-1
systemctl enable rsyslog

# CIS 5.1.3 Configure /etc/rsyslog.conf
### - cis-level-1
/etc/rsyslog.conf
auth,user.* /var/log/messages
kern.* /var/log/kern.log
daemon.* /var/log/daemon.log
syslog.* /var/log/syslog
lpr,news,uucp,local0,local1,local2,local3,local4,local5,local6.* /var/log/unused.log

# CIS 5.1.4 Create and Set Permissions on rsyslog Log Files
### - cis-level-1
chown root:root /var/log/messages
chmod og-rwx /var/log/messages
chown root:root /var/log/kern.log
chmod og-rwx /var/log/kern.log
chown root:root /var/log/daemon.log
chmod og-rwx /var/log/daemon.log
chown root:root /var/log/syslog
chmod og-rwx /var/log/syslog
chown root:root /var/log/unused.log
chmod og-rwx /var/log/unused.log
chown root:root /var/log/firewalld
chmod og-rwx /var/log/firewalld
chown root:root /var/log/secure
chmod og-rwx /var/log/secure
chown root:root /var/log/maillog
chmod og-rwx /var/log/maillog

# 5.1.5 Configure rsyslog to Send Logs to a Remote Log Host
### - cis-level-1
/etc/rsyslog.conf
*.* @@loghost.example.com

# CIS 5.1.6 Accept Remote rsyslog Messages Only on Designated Log Hosts
### - cis-level-1
/etc/rsyslog.conf
$ModLoad imtcp.so
$InputTCPServerRun 514

