- name: CIS 4.6 Uncommon Network Protocols
  debug: msg="*** Starting CIS section 4.6"
  tags:
    - cis-level-1
    - cis_4
    - cis_4.6
- name: Create /etc/modprobe.d/CIS.conf if it doesnt exist
  file: >
    path=/etc/modprobe.d/CIS.conf
    state=touch
    owner=root
    group=root
    mode=0600
  changed_when: false
  tags:
    - cis-level-1
    - cis_4
    - cis_4.6
    - cis_4.6.1
    - cis_4.6.2
    - cis_4.6.3
    - cis_4.6.4
- name: CIS 4.6.1 Disable DCCP
  lineinfile: >
    state=present
    dest=/etc/modprobe.d/CIS.conf
    line="install dccp /bin/true"
  tags:
    - cis-level-1
    - cis_4
    - cis_4.6
    - cis_4.6.1
- name: CIS 4.6.2 Disable SCTP
  lineinfile: >
    state=present
    dest=/etc/modprobe.d/CIS.conf
    line="install sctp /bin/true"
  tags:
    - cis-level-1
    - cis_4
    - cis_4.6
    - cis_4.6.2
- name: CIS 4.6.3 Disable RDS
  lineinfile: >
    state=present
    dest=/etc/modprobe.d/CIS.conf
    line="install rds /bin/true"
  tags:
    - cis-level-1
    - cis_4
    - cis_4.6
    - cis_4.6.3
- name: CIS 4.6.4 Disable TIPC
  lineinfile: >
    state=present
    dest=/etc/modprobe.d/CIS.conf
    line="install tipc /bin/true"
  tags:
    - cis-level-1
    - cis_4
    - cis_4.6
    - cis_4.6.4