- name: CIS 5.2 Configure System Accounting (auditd)
  debug: msg="*** Starting CIS section 5.2"
  tags:
    - cis-level-1
    - cis-level-2
    - cis_5
    - cis_5.2
- name: CIS 5.2 Install audit (installation)
  yum: >
    name=audit
    state=present
  tags:
    - cis-level-1
    - cis_5
    - cis_5.2
- name: CIS 5.2.1 Configure Data Retention
  debug: msg="*** Starting CIS section 5.2.1"
  tags:
    - cis-level-1
    - cis-level-2
    - cis_5
    - cis_5.2
- name: CIS 5.2.1.1 Configure Audit Log Storage Size
  lineinfile: >
    state=present
    dest=/etc/audit/auditd.conf
    regexp='^max_log_file = '
    line='max_log_file = {{audit_max_log_file}}'
  when: audit_max_log_file is defined
  tags:
    - cis-level-2
    - cis_5
    - cis_5.2
    - cis_5.2.1
    - cis_5.2.1.1
- name: CIS 5.2.1.2 Disable System on Audit Log Full (space_left_action)
  lineinfile: >
    state=present
    dest=/etc/audit/auditd.conf
    regexp='^space_left_action = '
    line='space_left_action = email'
  when: audit_max_log_file is defined
  tags:
    - cis-level-2
    - cis_5
    - cis_5.2
    - cis_5.2.1
    - cis_5.2.1.2
- name: CIS 5.2.1.2 Disable System on Audit Log Full (action_mail_acct)
  lineinfile: >
    state=present
    dest=/etc/audit/auditd.conf
    regexp='^action_mail_acct = '
    line='action_mail_acct = {{audit_action_mail_acct}}'
  when: audit_action_mail_acct is defined
  tags:
    - cis-level-2
    - cis_5
    - cis_5.2
    - cis_5.2.1
    - cis_5.2.1.2
- name: CIS 5.2.1.2 Disable System on Audit Log Full (admin_space_left_action)
  lineinfile: >
    state=present
    dest=/etc/audit/auditd.conf
    regexp='^admin_space_left_action = '
    line='admin_space_left_action = halt'
  tags:
    - cis-level-2
    - cis_5
    - cis_5.2
    - cis_5.2.1
    - cis_5.2.1.2
- name: CIS 5.2.1.3 Keep All Auditing Information
  lineinfile: >
    state=present
    dest=/etc/audit/auditd.conf
    regexp='^max_log_file_action = '
    line='max_log_file_action = keep_logs'
  tags:
    - cis-level-2
    - cis_5
    - cis_5.2
    - cis_5.2.1
    - cis_5.2.1.3
- name: CIS 5.2.2 Enable auditd Service
  service: >
    name=auditd
    state=started
    enabled=yes
  tags:
    - cis-level-2
    - cis_5
    - cis_5.2
    - cis_5.2.2
- name: CIS 5.2.3 Enable Auditing for Processes That Start Prior to auditd (configure)
  lineinfile: >
    state=present
    backrefs=yes
    dest=/etc/default/grub
    regexp='(^GRUB_CMDLINE_LINUX=.*\srhgb\squiet)(?<!audit=1)'
    line='\1 audit=1\"'
  register: grub_audit
  tags:
    - cis-level-2
    - cis_5
    - cis_5.2
    - cis_5.2.3
- name: CIS 5.2.3 Enable Auditing for Processes That Start Prior to auditd (make grub)
  command: grub2-mkconfig -o /boot/grub2/grub.cfg
  when: grub_audit.changed
  tags:
    - cis-level-2
    - cis_5
    - cis_5.2
    - cis_5.2.3
- name: CIS 5.2.4 - 5.2.18 (excluding 5.2.12) Deploying audit.rules
  template: >
    src=templates/audit.rules.j2
    dest=/etc/audit/rules.d/audit.rules
    owner=root
    group=root
    mode=0644
  tags:
    - cis-level-2
    - cis_5
    - cis_5.2
    - cis_5.2.4
    - cis_5.2.5
    - cis_5.2.6
    - cis_5.2.7
    - cis_5.2.8
    - cis_5.2.9
    - cis_5.2.10
    - cis_5.2.11
    - cis_5.2.13
    - cis_5.2.14
    - cis_5.2.15
    - cis_5.2.16
    - cis_5.2.17
    - cis_5.2.18
# CIS 5.2.12 Collect Use of Privileged Commands
### - cis-level-2
#All audit records will be tagged with the identifier "privileged."
#find PART -xdev \( -perm -4000 -o -perm -2000 \) -type f | awk '{print "-a always,exit -F path=" $1 " -F perm=x -F auid>=1000 -F auid!=4294967295 -k privileged" }'
#Next, add those lines to the /etc/audit/audit.rules file.
