- name: CIS 1.4 Configure SELinux
  debug: msg="*** Starting CIS section 1.4"
- name: CIS 1.4.1 Enable SELinux in /boot/grub2/grub.cfg (selinux=0)
  lineinfile: >
    state=absent
    dest=/boot/grub2/grub.cfg
    line="selinux=0"
  tags:
    - cis-level-2
    - cis_1.4
    - cis_1.4.1
- name: CIS 1.4.1 Enable SELinux in /boot/grub2/grub.cfg (enforcing=0)
  lineinfile: >
    state=absent
    dest=/boot/grub2/grub.cfg
    line="enforcing=0"
  tags:
    - cis-level-2
    - cis_1.4
    - cis_1.4.1
- name: CIS 1.4.2 + 1.4.3 Set the SELinux State and Policy
  selinux: >
    state=enforcing
    policy=targeted
  ignore_errors: yes
  tags:
    - cis-level-2
    - cis_1.4
    - cis_1.4.2
    - cis_1.4.3
- name: CIS 1.4.4 Remove SETroubleshoot
  yum: >
    name=setroubleshoot
    state=absent
  tags:
    - cis-level-2
    - cis_1.4
    - cis_1.4.4
- name: CIS 1.4.5 Remove MCS Translation Service (mcstrans)
  yum: >
    name=mcstrans
    state=absent
  tags:
    - cis-level-2
    - cis_1.4
    - cis_1.4.5
- name: CIS 1.4.6 Check for Unconfined Daemons
  debug: msg="*** Check manually."
  tags:
    - cis-level-2
    - cis_1.4
    - cis_1.4.6
