- name: CIS 4.6 Uncommon Network Protocols
  debug: msg="*** Starting CIS section 4.6"
- name: CIS 4.6.1 Disable DCCP
  lineinfile: >
    state=present
    dest=/etc/modprobe.d/CIS.conf
    line="install dccp /bin/true"
  tags:
    - cis-level-1
    - cis-sec_4.6
    - cis-sec_4.6.1
- name: CIS 4.6.2 Disable SCTP
  lineinfile: >
    state=present
    dest=/etc/modprobe.d/CIS.conf
    line="install sctp /bin/true"
  tags:
    - cis-level-1
    - cis-sec_4.6
    - cis-sec_4.6.2
- name: CIS 4.6.3 Disable RDS
  lineinfile: >
    state=present
    dest=/etc/modprobe.d/CIS.conf
    line="install rds /bin/true"
  tags:
    - cis-level-1
    - cis-sec_4.6
    - cis-sec_4.6.3
- name: CIS 4.6.4 Disable TIPC
  lineinfile: >
    state=present
    dest=/etc/modprobe.d/CIS.conf
    line="install tipc /bin/true"
  tags:
    - cis-level-1
    - cis-sec_4.6
    - cis-sec_4.6.4
