- name: CIS 6.1 Remove Legacy Services
  debug: msg="*** Starting CIS section 6.1"
- name: CIS 6.1 Configure cron and anacron
  debug: msg="*** Starting CIS section 6.1"
- name: CIS 6.1.1 Enable anacron Daemon
  yum: >
    name=cronie-anacron
    state=present
  tags:
    - cis-level-1
    - cis_6.1
    - cis_6.1.1
- name: CIS 6.1.2 Enable crond Daemon
  service: >
    name=crond
    state=started
    enabled=yes
  tags:
    - cis-level-1
    - cis_6.1
    - cis_6.1.2
- name: CIS 6.1.3 Set User/Group Owner and Permission on /etc/anacrontab
  file: >
    path=/etc/anacrontab
    state=touch
    owner=root
    group=root
    mode=0600
  changed_when: false
  tags:
    - cis-level-1
    - cis_6.1
    - cis_6.1.3
- name: CIS 6.1.4 Set User/Group Owner and Permission on /etc/crontab
  file: >
    path=/etc/crontab
    state=touch
    owner=root
    group=root
    mode=0600
  changed_when: false
  tags:
    - cis-level-1
    - cis_6.1
    - cis_6.1.4
- name: CIS 6.1.5 Set User/Group Owner and Permission on /etc/cron.hourly
  file: >
    path=/etc/cron.hourly
    state=touch
    owner=root
    group=root
    mode=0600
  changed_when: false
  tags:
    - cis-level-1
    - cis_6.1
    - cis_6.1.5
- name: CIS 6.1.6 Set User/Group Owner and Permission on /etc/cron.daily
  file: >
    path=/etc/cron.daily
    state=touch
    owner=root
    group=root
    mode=0600
  changed_when: false
  tags:
    - cis-level-1
    - cis_6.1
    - cis_6.1.6
- name: CIS 6.1.7 Set User/Group Owner and Permission on /etc/cron.weekly
  file: >
    path=/etc/cron.weekly
    state=touch
    owner=root
    group=root
    mode=0600
  changed_when: false
  tags:
    - cis-level-1
    - cis_6.1
    - cis_6.1.7
- name: CIS 6.1.8 Set User/Group Owner and Permission on /etc/cron.monthly
  file: >
    path=/etc/cron.monthly
    state=touch
    owner=root
    group=root
    mode=0600
  changed_when: false
  tags:
    - cis-level-1
    - cis_6.1
    - cis_6.1.8
- name: CIS 6.1.9 Set User/Group Owner and Permission on /etc/cron.d
  file: >
    path=/etc/cron.d
    state=touch
    owner=root
    group=root
    mode=0600
  changed_when: false
  tags:
    - cis-level-1
    - cis_6.1
    - cis_6.1.9
- name: CIS 6.1.10 Restrict at Daemon remove (at.deny)
  file: >
    path=/etc/at.deny
    state=absent
  tags:
    - cis-level-1
    - cis_6.1
    - cis_6.1.10
- name: CIS 6.1.10 Restrict at Daemon remove (at.allow)
  file: >
    path=/etc/at.allow
    state=touch
    owner=root
    group=root
    mode='og-rwx'
  tags:
    - cis-level-1
    - cis_6.1
    - cis_6.1.10
- name: CIS 6.1.11 Restrict at/cron to Authorized Users (cron.deny)
  file: >
    path=/etc/cron.deny
    state=absent
  tags:
    - cis-level-1
    - cis_6.1
    - cis_6.1.11
- name: CIS 6.1.11 Restrict at/cron to Authorized Users (cron.allow)
  file: >
    path=/etc/cron.allow
    state=touch
    owner=root
    group=root
    mode='og-rwx'
  tags:
    - cis-level-1
    - cis_6.1
    - cis_6.1.11
