## CIS 5.1 Configure rsyslog
- name: CIS 5.1.1 Install the rsyslog package
  yum: >
    name=rsyslog
    state=present
  tags:
    - cis-level-1
    - cis-sec_5.1
    - cis-sec_5.1.1
- name: CIS 5.1.2 Activate the rsyslog Service
  service: >
    name=rsyslog
    state=started
    enabled=yes
  tags:
    - cis-level-1
    - cis-sec_5
    - cis-sec_5.1
    - cis-sec_5.1.2


# CIS 5.1.3 Configure /etc/rsyslog.conf
### - cis-level-1
/etc/rsyslog.conf
auth,user.* /var/log/messages
kern.* /var/log/kern.log
daemon.* /var/log/daemon.log
syslog.* /var/log/syslog
lpr,news,uucp,local0,local1,local2,local3,local4,local5,local6.* /var/log/unused.log


- name: CIS 5.1.4 Create and Set Permissions on rsyslog Log Files
  file: >
    path=/var/log/{{item}}
    state=touch
    owner=root
    group=wheel
    mode=0640
  with_items:
    - messages
    - kern.log
    - daemon.log
    - syslog
    - unused.log
		- firewalld
		- secure
		- maillog
  tags:
    - cis-level-1
    - cis-sec_5.1
    - cis-sec_5.1.4

# 5.1.5 Configure rsyslog to Send Logs to a Remote Log Host
### - cis-level-1
/etc/rsyslog.conf
*.* @@loghost.example.com

# CIS 5.1.6 Accept Remote rsyslog Messages Only on Designated Log Hosts
### - cis-level-1
/etc/rsyslog.conf
$ModLoad imtcp.so
$InputTCPServerRun 514

