- name: CIS 1.3 Advanced Intrusion Detection Environment (AIDE)
  debug: msg="*** Starting CIS section 1.3"
- name: CIS 1.3.1 Install AIDE part 1
  yum: >
    name=aide
    state=present
  tags:
    - cis-level-1
    - cis-sec_1.3
    - cis-sec_1.3.1
- name: CIS 1.3.1 Install AIDE part 2
  command: >
    /usr/sbin/aide --init -B 'database_out=file:/var/lib/aide/aide.db.gz'
    creates=/var/lib/aide/aide.db.gz
  tags:
    - cis-level-1
    - cis-sec_1.3
    - cis-sec_1.3.1
- name: CIS 1.3.1 Install AIDE part 3
  command: /usr/sbin/prelink -ua
  tags:
    - cis-level-1
    - cis-sec_1.3
    - cis-sec_1.3.1
- name: CIS 1.3.2 Implement Periodic Execution of File Integrity
  cron: >
    name="CIS 1.3.2 (AIDE)"
    minute="0"
    hour="5"
    job="/usr/sbin/aide --check"
  tags:
    - cis-level-1
    - cis-sec_1.3
    - cis-sec_1.3.2
