## CIS 6.1 Configure cron and anacron
# CIS 6.1.1 Enable anacron Daemon
### - cis-level-1
yum install cronie-anacron

# CIS 6.1.2 Enable crond Daemon
### - cis-level-1
systemctl enable crond

# CIS 6.1.3 Set User/Group Owner and Permission on /etc/anacrontab
### - cis-level-1
chown root:root /etc/anacrontab
chmod og-rwx /etc/anacrontab

# CIS 6.1.4 Set User/Group Owner and Permission on /etc/crontab
### - cis-level-1
chown root:root /etc/crontab
chmod og-rwx /etc/crontab

# CIS 6.1.5 Set User/Group Owner and Permission on /etc/cron.hourly
### - cis-level-1
chown root:root /etc/cron.hourly
chmod og-rwx /etc/cron.hourly

# CIS 6.1.6 Set User/Group Owner and Permission on /etc/cron.daily
### - cis-level-1
chown root:root /etc/cron.daily
chmod og-rwx /etc/cron.daily

# CIS 6.1.7 Set User/Group Owner and Permission on /etc/cron.weekly
### - cis-level-1
chown root:root /etc/cron.weekly
chmod og-rwx /etc/cron.weekly

# CIS 6.1.8 Set User/Group Owner and Permission on /etc/cron.monthly 
### - cis-level-1
chown root:root /etc/cron.monthly
chmod og-rwx /etc/cron.monthly

# CIS 6.1.9 Set User/Group Owner and Permission on /etc/cron.d
### - cis-level-1
chown root:root /etc/cron.d
chmod og-rwx /etc/cron.d

# CIS 6.1.10 Restrict at Daemon
### - cis-level-1
rm /etc/at.deny
touch /etc/at.allow
chown root:root /etc/at.allow
chmod og-rwx /etc/at.allow

# CIS 6.1.11 Restrict at/cron to Authorized Users 
### - cis-level-1
/bin/rm /etc/cron.deny
/bin/rm /etc/at.deny
chmod og-rwx /etc/cron.allow
chmod og-rwx /etc/at.allow
chown root:root /etc/cron.allow
chown root:root /etc/at.allow

