## CIS 4.5 Install TCP Wrappers
- name: CIS 4.5.1 Install TCP Wrappers
  yum: >
    name=tcp_wrappers
    state=present
  tags:
    - cis-level-1
    - cis-sec_4.5
    - cis-sec_4.5.1
- name: CIS 4.5.2 Create /etc/hosts.allow
  lineinfile: >
    state=present
    create=yes
    dest=/etc/hosts.allow
    regexp=^ALL
    line=ALL:{{ tcp_allow | default("ALL") }}
  tags:
    - cis-level-1
    - cis-sec_4.5
    - cis-sec_4.5.2
- name: CIS 4.5.3 Verify Permissions on /etc/hosts.allow
  file: >
    path=/etc/hosts.allow
    owner=root
    group=root
    mode=0644
  tags:
    - cis-level-1
    - cis-sec_4.5
    - cis-sec_4.5.3
- name: CIS 4.5.4 Create /etc/hosts.deny
  lineinfile: >
    state=present
    create=yes
    dest=/etc/hosts.deny
    line="ALL: ALL"
  tags:
    - cis-level-1
    - cis-sec_4.5
    - cis-sec_4.5.4
- name: CIS 4.5.5 Verify Permissions on /etc/hosts.deny
  file: >
    path=/etc/hosts.deny
    owner=root
    group=root
    mode=0644
  tags:
    - cis-level-1
    - cis-sec_4.5
    - cis-sec_4.5.5
