- name: CIS 5.2 Configure System Accounting (auditd)
  debug: msg="*** Starting CIS section 5.2"
- name: CIS 5.2 Install audit (installation)
  yum: >
    name=audit
    state=present
  tags:
    - cis-level-1
    - cis_5.2
# CIS 5.2.1 Configure Data Retention
# CIS 5.2.1.1 Configure Audit Log Storage Size
### - cis-level-2
/etc/audit/auditd.conf
max_log_file = <MB>

# CIS 5.2.1.2 Disable System on Audit Log Full
### - cis-level-2
/etc/audit/auditd.conf
space_left_action = email
action_mail_acct = root
admin_space_left_action = halt

# CIS 5.2.1.3 Keep All Auditing Information
### - cis-level-2
/etc/audit/auditd.conf
max_log_file_action = keep_logs

# CIS 5.2.2 Enable auditd Service
### - cis-level-2
systemctl enable auditd

# CIS 5.2.3 Enable Auditing for Processes That Start Prior to auditd
### - cis-level-2
/etc/default/grub
GRUB_CMDLINE_LINUX="audit=1"
grub2-mkconfig -o /boot/grub2/grub.cfg

# CIS 5.2.4 Record Events That Modify Date and Time Information
### - cis-level-2
/etc/audit/audit.rules
-a always,exit -F arch=b64 -S adjtimex -S settimeofday -k time-change
-a always,exit -F arch=b32 -S adjtimex -S settimeofday -S stime -k time-change
-a always,exit -F arch=b64 -S clock_settime -k time-change
-a always,exit -F arch=b32 -S clock_settime -k time-change
-w /etc/localtime -p wa -k time-change

# CIS 5.2.5 Record Events That Modify User/Group Information
### - cis-level-2
/etc/audit/audit.rules
-w /etc/group -p wa -k identity
-w /etc/passwd -p wa -k identity
-w /etc/gshadow -p wa -k identity
-w /etc/shadow -p wa -k identity
-w /etc/security/opasswd -p wa -k identity

# CIS 5.2.6 Record Events That Modify the System's Network Environment
### - cis-level-2
/etc/audit/audit.rules
-a always,exit -F arch=b64 -S sethostname -S setdomainname -k system-locale
-a always,exit -F arch=b32 -S sethostname -S setdomainname -k system-locale
-w /etc/issue -p wa -k system-locale
-w /etc/issue.net -p wa -k system-locale
-w /etc/hosts -p wa -k system-locale
-w /etc/sysconfig/network -p wa -k system-locale

# CIS 5.2.7 Record Events That Modify the System's Mandatory Access Controls
### - cis-level-2
/etc/audit/audit.rules
-w /etc/selinux/ -p wa -k MAC-policy

# CIS 5.2.8 Collect Login and Logout Events
### - cis-level-2
/etc/audit/audit.rules
-w /var/log/faillog -p wa -k logins
-w /var/log/lastlog -p wa -k logins
-w /var/log/tallylog -p wa -k logins

# CIS 5.2.9 Collect Session Initiation Information
### - cis-level-2
/etc/audit/audit.rules
-w /var/run/utmp -p wa -k session
-w /var/log/wtmp -p wa -k session
-w /var/log/btmp -p wa -k session

# CIS 5.2.10 Collect Discretionary Access Control Permission Modification Events
### - cis-level-2
/etc/audit/audit.rules
-a always,exit -F arch=b64 -S chmod -S fchmod -S fchmodat -F auid>=1000 \
-F auid!=4294967295 -k perm_mod
-a always,exit -F arch=b32 -S chmod -S fchmod -S fchmodat -F auid>=1000 \
-F auid!=4294967295 -k perm_mod
-a always,exit -F arch=b64 -S chown -S fchown -S fchownat -S lchown -F auid>=1000 \
-F auid!=4294967295 -k perm_mod
-a always,exit -F arch=b32 -S chown -S fchown -S fchownat -S lchown -F auid>=1000 \
-F auid!=4294967295 -k perm_mod
-a always,exit -F arch=b64 -S setxattr -S lsetxattr -S fsetxattr -S removexattr -S \
lremovexattr -S fremovexattr -F auid>=1000 -F auid!=4294967295 -k perm_mod
-a always,exit -F arch=b32 -S setxattr -S lsetxattr -S fsetxattr -S removexattr -S \
lremovexattr -S fremovexattr -F auid>=1000 -F auid!=4294967295 -k perm_mod

# CIS 5.2.11 Collect Unsuccessful Unauthorized Access Attempts to Files
### - cis-level-2
/etc/audit/audit.rules
-a always,exit -F arch=b64 -S creat -S open -S openat -S truncate -S ftruncate \
-F exit=-EACCES -F auid>=1000 -F auid!=4294967295 -k access
-a always,exit -F arch=b32 -S creat -S open -S openat -S truncate -S ftruncate \
-F exit=-EACCES -F auid>=1000 -F auid!=4294967295 -k access
-a always,exit -F arch=b64 -S creat -S open -S openat -S truncate -S ftruncate \
-F exit=-EPERM -F auid>=1000 -F auid!=4294967295 -k access
-a always,exit -F arch=b32 -S creat -S open -S openat -S truncate -S ftruncate \
-F exit=-EPERM -F auid>=1000 -F auid!=4294967295 -k access

# CIS 5.2.12 Collect Use of Privileged Commands
### - cis-level-2
All audit records will be tagged with the identifier "privileged."
find PART -xdev \( -perm -4000 -o -perm -2000 \) -type f | awk '{print "-a always,exit -F path=" $1 " -F perm=x -F auid>=1000 -F auid!=4294967295 -k privileged" }'
Next, add those lines to the /etc/audit/audit.rules file.

# CIS 5.2.13 Collect Successful File System Mounts
### - cis-level-2
/etc/audit/audit.rules
-a always,exit -F arch=b64 -S mount -F auid>=1000 -F auid!=4294967295 -k mounts
-a always,exit -F arch=b32 -S mount -F auid>=1000 -F auid!=4294967295 -k mounts

# CIS 5.2.14 Collect File Deletion Events by User
### - cis-level-2
/etc/audit/audit.rules
-a always,exit -F arch=b64 -S unlink -S unlinkat -S rename -S renameat -F auid>=1000 \
-F auid!=4294967295 -k delete
-a always,exit -F arch=b32 -S unlink -S unlinkat -S rename -S renameat -F auid>=1000 \
-F auid!=4294967295 -k delete

# CIS 5.2.15 Collect Changes to System Administration Scope (sudoers)
### - cis-level-2
/etc/audit/audit.rules
-w /etc/sudoers -p wa -k scope

# CIS 5.2.16 Collect System Administrator Actions (sudolog)
### - cis-level-2
/etc/audit/audit.rules
-w /var/log/sudo.log -p wa -k actions

# CIS 5.2.17 Collect Kernel Module Loading and Unloading
### - cis-level-2
/etc/audit/audit.rules
-w /sbin/insmod -p x -k modules
-w /sbin/rmmod -p x -k modules
-w /sbin/modprobe -p x -k modules
-a always,exit -F arch=b64 -S init_module -S delete_module -k modules

# CIS 5.2.18 Make the Audit Configuration Immutable
### - cis-level-2
/etc/audit/audit.rules
-e 2

