- name: CIS 2.1 Remove Legacy Services
  debug: msg="*** Starting CIS section 2.1"
- name: CIS 2.1.1 Remove telnet-server
  yum: >
    name=telnet-server
    state=absent
  tags:
    - cis-level-1
    - cis_2
    - cis_2.1
    - cis_2.1.1
- name: CIS 2.1.2 Remove telnet Clients
  yum: >
    name=telnet
    state=absent
  tags:
    - cis-level-1
    - cis_2
    - cis_2.1
    - cis_2.1.2
- name: CIS 2.1.3 Remove rsh-server
  yum: >
    name=rsh-server
    state=absent
  tags:
    - cis-level-1
    - cis_2
    - cis_2.1
    - cis_2.1.3
- name: CIS 2.1.4 Remove rsh
  yum: >
    name=rsh
    state=absent
  tags:
    - cis-level-1
    - cis_2
    - cis_2.1
    - cis_2.1.4
- name: CIS 2.1.5 Remove NIS Client
  yum: >
    name=ypbind
    state=absent
  tags:
    - cis-level-1
    - cis_2
    - cis_2.1
    - cis_2.1.5
- name: CIS 2.1.6 Remove NIS Server
  yum: >
    name=ypserv
    state=absent
  tags:
    - cis-level-1
    - cis_2
    - cis_2.1
    - cis_2.1.6
- name: CIS 2.1.7 Remove tftp
  yum: >
    name=tftp
    state=absent
  tags:
    - cis-level-1
    - cis_2
    - cis_2.1
    - cis_2.1.7
- name: CIS 2.1.8 Remove tftp-server
  yum: >
    name=tftp-server
    state=absent
  tags:
    - cis-level-1
    - cis_2
    - cis_2.1
    - cis_2.1.8
- name: CIS 2.1.9 Remove talk
  yum: >
    name=talk
    state=absent
  tags:
    - cis-level-1
    - cis_2
    - cis_2.1
    - cis_2.1.9
- name: CIS 2.1.10 Remove talk-server
  yum: >
    name=talk-server
    state=absent
  tags:
    - cis-level-1
    - cis_2
    - cis_2.1
    - cis_2.1.10
- name: CIS 2.1.11 Remove xinetd
  yum: >
    name=xinetd
    state=absent
  tags:
    - cis-level-2
    - cis_2
    - cis_2.1
    - cis_2.1.11
- name: CIS 2.1.12 Disable chargen-dgram (check if exists)
  stat: path=/etc/xinetd.d/chargen-dgram
  register: chargen_dgram
  tags:
    - cis-level-1
    - cis_2
    - cis_2.1
    - cis_2.1.12
- name: CIS 2.1.12 Disable chargen-dgram (disable xinetd service)
  service: >
    name=chargen-dgram
    state=stopped
    enabled=no
  when: chargen_dgram.stat.exists
  tags:
    - cis-level-1
    - cis_2
    - cis_2.1
    - cis_2.1.12
- name: CIS 2.1.13 Disable chargen-stream (check if exists)
  stat: path=/etc/xinetd.d/chargen-stream
  register: chargen_stream
  tags:
    - cis-level-1
    - cis_2
    - cis_2.1
    - cis_2.1.13
- name: CIS 2.1.13 Disable chargen-stream (disable xinetd service)
  service: >
    name=chargen-stream
    state=stopped
    enabled=no
  when: chargen_stream.stat.exists
  tags:
    - cis-level-1
    - cis_2
    - cis_2.1
    - cis_2.1.13
- name: CIS 2.1.14 Disable daytime-dgram (check if exists)
  stat: path=/etc/xinetd.d/daytime-dgram
  register: daytime_dgram
  tags:
    - cis-level-1
    - cis_2
    - cis_2.1
    - cis_2.1.14
- name: CIS 2.1.14 Disable daytime-dgram (disable xinetd service)
  service: >
    name=daytime-dgram
    state=stopped
    enabled=no
  when: daytime_dgram.stat.exists
  tags:
    - cis-level-1
    - cis_2
    - cis_2.1
    - cis_2.1.14
- name: CIS 2.1.15 Disable daytime-stream (check if exists)
  stat: path=/etc/xinetd.d/daytime-stream
  register: daytime_stream
  tags:
    - cis-level-1
    - cis_2
    - cis_2.1
    - cis_2.1.15
- name: CIS 2.1.15 Disable daytime-stream (disable xinetd service)
  service: >
    name=daytime-stream
    state=stopped
    enabled=no
  when: daytime_stream.stat.exists
  tags:
    - cis-level-1
    - cis_2
    - cis_2.1
    - cis_2.1.15
- name: CIS 2.1.16 Disable echo-dgram (check if exists)
  stat: path=/etc/xinetd.d/echo-dgram
  register: echo_dgram
  tags:
    - cis-level-1
    - cis_2
    - cis_2.1
    - cis_2.1.16
- name: CIS 2.1.16 Disable echo-dgram (disable xinetd service)
  service: >
    name=echo-dgram
    state=stopped
    enabled=no
  when: echo_dgram.stat.exists
  tags:
    - cis-level-1
    - cis_2
    - cis_2.1
    - cis_2.1.16
- name: CIS 2.1.17 Disable echo-stream (check if exists)
  stat: path=/etc/xinetd.d/echo-stream
  register: echo_stream
  tags:
    - cis-level-1
    - cis_2
    - cis_2.1
    - cis_2.1.17
- name: CIS 2.1.17 Disable echo-stream (disable xinetd service)
  service: >
    name=echo-stream
    state=stopped
    enabled=no
  when: echo_stream.stat.exists
  tags:
    - cis-level-1
    - cis_2
    - cis_2.1
    - cis_2.1.17
- name: CIS 2.1.18 Disable tcpmux-server (check if exists)
  stat: path=/etc/xinetd.d/tcpmux-server
  register: tcpmux_server
  tags:
    - cis-level-1
    - cis_2
    - cis_2.1
    - cis_2.1.18
- name: CIS 2.1.18 Disable tcpmux-server (disable xinetd service)
  service: >
    name=tcpmux-server
    state=stopped
    enabled=no
  when: tcpmux_server.stat.exists
  tags:
    - cis-level-1
    - cis_2
    - cis_2.1
    - cis_2.1.18