- name: CIS 1.1 Filesystem Configuration
  debug: msg="*** Starting CIS section 1.1"
- name: CIS 1.1.1 Create Separate Partition for /tmp
  debug: msg="*** Manually create Separate Partition for /tmp."
  tags:
    - cis-level-1
    - cis-sec_1.1
    - cis-sec_1.1.1
- name: CIS 1.1.2 - 1.1.4 Set nodev,nosuid,noexec option for /tmp Partition
  mount: >
    name="/tmp"
    src={{ item.device }}
    state=present
    fstype={{ item.fstype }}
    opts="nodev,nosuid,noexec"
  when: item.mount == "/tmp"
  with_items: ansible_mounts
  tags:
    - cis-level-1
    - cis-sec_1.1
    - cis-sec_1.1.2
    - cis-sec_1.1.3
    - cis-sec_1.1.4
- name: CIS 1.1.5 Create Separate Partition for /var
  debug: msg="*** Manually create Separate Partition for /var"
  tags:
    - cis-level-1
    - cis-sec_1.1
    - cis-sec_1.1.5
- name: CIS 1.1.6 Bind Mount the /var/tmp directory to /tmp
  mount: >
    name="/var/tmp"
    src="/tmp"
    state=present
    fstype="none"
    opts="bind"
  when: item.mount == "/tmp"
  with_items: ansible_mounts
  tags:
    - cis-level-1
    - cis-sec_1.1
    - cis-sec_1.1.6
- name: CIS 1.1.7 Create Separate Partition for /var/log
  debug: msg="*** Manually create Separate Partition for /var/log"
  tags:
    - cis-level-1
    - cis-sec_1.1
    - cis-sec_1.1.7
- name: CIS 1.1.8 Create Separate Partition for /var/log/audit
  debug: msg="*** Manually create Separate Partition for /var/log/audit"
  tags:
    - cis-level-1
    - cis-sec_1.1
    - cis-sec_1.1.8
- name: CIS 1.1.9 Create Separate Partition for /home
  debug: msg="*** Manually create Separate Partition for /home"
  tags:
    - cis-level-1
    - cis-sec_1.1
    - cis-sec_1.1.9
- name: CIS 1.1.10 Add nodev Option to /home
  mount: >
    name="/home"
    src={{ item.device }}
    state=present
    fstype={{ item.fstype }}
    opts="nodev"
  when: item.mount == "/home"
  with_items: ansible_mounts
  tags:
    - cis-level-1
    - cis-sec_1.1
    - cis-sec_1.1.10
- name: CIS 1.1.11 Add nodev Option to Removable Media Partitions
  debug: msg="*** Not needed."
  tags:
    - cis-level-1
    - cis-sec_1.1
    - cis-sec_1.1.11
- name: CIS 1.1.12 Add noexec Option to Removable Media Partitions
  debug: msg="*** Not needed."
  tags:
    - cis-level-1
    - cis-sec_1.1
    - cis-sec_1.1.12
- name: CIS 1.1.13 Add nosuid Option to Removable Media Partitions
  debug: msg="*** Not needed."
  tags:
    - cis-level-1
    - cis-sec_1.1
    - cis-sec_1.1.13

- name: CIS 1.1.14 - 1.1.16 Set nodev,nosuid,noexec option for /dev/shm Partition
  mount: >
    name="/dev/shm"
    src={{ item.device }}
    state=present
    fstype={{ item.fstype }}
    opts="nodev,nosuid,noexec"
  when: item.mount == "/dev/shm"
  with_items: ansible_mounts
  tags:
    - cis-level-1
    - cis-sec_1.1
    - cis-sec_1.1.14
    - cis-sec_1.1.15
    - cis-sec_1.1.16
- name: CIS 1.1.17 Set Sticky Bit on All World-Writable Directories
  debug: msg="*** Manual intervension needed on this could be dangerous"
  tags:
    - cis-level-1
    - cis-sec_1.1
    - cis-sec_1.1.17
- name: Create /etc/modprobe.d/CIS.conf with root ownership & mode
  file: >
    path=/etc/modprobe.d/CIS.conf
    state=touch
    owner=root
    group=root
    mode=0600
  changed_when: false
  tags:
    - cis-level-1
    - cis-sec_1.1
    - cis-sec_1.1.18
    - cis-sec_1.1.19
    - cis-sec_1.1.20
    - cis-sec_1.1.21
    - cis-sec_1.1.22
    - cis-sec_1.1.23
    - cis-sec_1.1.24
- name: CIS 1.1.18 Disable Mounting of cramfs Filesystems
  lineinfile: >
    state=present
    dest=/etc/modprobe.d/CIS.conf
    line="install cramfs /bin/true"
  tags:
    - cis-level-2
    - cis-sec_1.1
    - cis-sec_1.1.18
- name: CIS 1.1.19 Disable Mounting of freevxfs Filesystems
  lineinfile: >
    state=present
    dest=/etc/modprobe.d/CIS.conf
    line="install freevxfs /bin/true"
  tags:
    - cis-level-2
    - cis-sec_1.1
    - cis-sec_1.1.19
- name: CIS 1.1.20 Disable Mounting of jffs2 Filesystems
  lineinfile: >
    state=present
    dest=/etc/modprobe.d/CIS.conf
    line="install jffs2 /bin/true"
  tags:
    - cis-level-2
    - cis-sec_1.1
    - cis-sec_1.1.20
- name: CIS 1.1.21 Disable Mounting of hfs Filesystems
  lineinfile: >
    state=present
    dest=/etc/modprobe.d/CIS.conf
    line="install hfs /bin/true"
  tags:
    - cis-level-2
    - cis-sec_1.1
    - cis-sec_1.1.21
- name: CIS 1.1.22 Disable Mounting of hfsplus Filesystems
  lineinfile: >
    state=present
    dest=/etc/modprobe.d/CIS.conf
    line="install hfsplus /bin/true"
  tags:
    - cis-level-2
    - cis-sec_1.1
    - cis-sec_1.1.22
- name: CIS 1.1.23 Disable Mounting of squashfs Filesystems
  lineinfile: >
    state=present
    dest=/etc/modprobe.d/CIS.conf
    line="install squashfs /bin/true"
  tags:
    - cis-level-2
    - cis-sec_1.1
    - cis-sec_1.1.23
- name: CIS 1.1.24 Disable Mounting of udf Filesystems
  lineinfile: >
    state=present
    dest=/etc/modprobe.d/CIS.conf
    line="install udf /bin/true"
  tags:
    - cis-level-2
    - cis-sec_1.1
    - cis-sec_1.1.24
