## CIS 4.1 Modify Network Parameters
- name: CIS 4.1.1 Disable IP Forwarding
  sysctl: >
    name=net.ipv4.ip_forward
    value=0
    state=present
    ignoreerrors=yes
  tags:
    - cis-level-1
    - cis-sec_4.1
    - cis-sec_4.1.1
- name: CIS 4.1.2 Disable Send Packet Redirects (net.ipv4.conf.all.send_redirects)
  sysctl: >
    name=net.ipv4.conf.all.send_redirects
    value=0
    state=present
    ignoreerrors=yes
  tags:
    - cis-level-1
    - cis-sec_4.1
    - cis-sec_4.1.2
- name: CIS 4.1.2 Disable Send Packet Redirects (net.ipv4.conf.default.send_redirects)
  sysctl: >
    name=net.ipv4.conf.default.send_redirects
    value=0
    state=present
    ignoreerrors=yes
  tags:
    - cis-level-1
    - cis-sec_4.1
    - cis-sec_4.1.2