- name: CIS 1.2 Configure Software Updates
  debug: msg="*** Starting CIS section 1.2"
  tags:
    - cis-level-1
    - cis_1
    - cis_1.2
- name: CIS 1.2.1 Verify CentOS GPG Key is Installed
  rpm_key:
    state=present
    key=/etc/pki/rpm-gpg/RPM-GPG-KEY-CentOS-7
  tags:
    - cis-level-1
    - cis_1
    - cis_1.2
    - cis_1.2.1
- name: CIS 1.2.2 Verify that gpgcheck is Globally Activated
  lineinfile: >
    state=present
    dest=/etc/yum.conf
    regexp=^gpgcheck=
    line=gpgcheck=1
  tags:
    - cis-level-1
    - cis_1
    - cis_1.2
    - cis_1.2.2
- name: CIS 1.2.3 Obtain Software Package Updates with yum
  debug: msg="*** Check manually."
  tags:
    - cis-level-1
    - cis_1
    - cis_1.2
    - cis_1.2.3
- name: CIS 1.2.4 Verify Package Integrity Using RPM
  debug: msg="*** Check manually."
  tags:
    - cis-level-1
    - cis_1
    - cis_1.2
    - cis_1.2.3