- name: CIS 4.2 Modify Network Parameters (Host and Router)
  debug: msg="*** Starting CIS section 4.2"
- name: CIS 4.2.1 Disable Source Routed Packet Acceptance (net.ipv4.conf.all.accept_source_route)
  sysctl: >
    name=net.ipv4.conf.all.accept_source_route
    value=0
    state=present
    ignoreerrors=yes
    sysctl_file=/etc/sysctl.conf
  tags:
    - cis-level-1
    - cis_4.2
    - cis_4.2.1
- name: CIS 4.2.1 Disable Source Routed Packet Acceptance (net.ipv4.conf.default.accept_source_route)
  sysctl: >
    name=net.ipv4.conf.default.accept_source_route
    value=0
    state=present
    ignoreerrors=yes
    sysctl_file=/etc/sysctl.conf
  tags:
    - cis-level-1
    - cis_4.2
    - cis_4.2.1
- name: CIS 4.2.2 Disable ICMP Redirect Acceptance (net.ipv4.conf.all.accept_redirects)
  sysctl: >
    name=net.ipv4.conf.all.accept_redirects
    value=0
    state=present
    ignoreerrors=yes
    sysctl_file=/etc/sysctl.conf
  tags:
    - cis-level-1
    - cis_4.2
    - cis_4.2.2
- name: CIS 4.2.2 Disable ICMP Redirect Acceptance (net.ipv4.conf.default.accept_redirects)
  sysctl: >
    name=net.ipv4.conf.default.accept_redirects
    value=0
    state=present
    ignoreerrors=yes
    sysctl_file=/etc/sysctl.conf
  tags:
    - cis-level-1
    - cis_4.2
    - cis_4.2.2
- name: CIS 4.2.3 Disable Secure ICMP Redirect Acceptance (net.ipv4.conf.all.secure_redirects)
  sysctl: >
    name=net.ipv4.conf.all.secure_redirects
    value=0
    state=present
    ignoreerrors=yes
    sysctl_file=/etc/sysctl.conf
  tags:
    - cis-level-2
    - cis_4.2
    - cis_4.2.3
- name: CIS 4.2.3 Disable Secure ICMP Redirect Acceptance (net.ipv4.conf.default.secure_redirects)
  sysctl: >
    name=net.ipv4.conf.default.secure_redirects
    value=0
    state=present
    ignoreerrors=yes
    sysctl_file=/etc/sysctl.conf
  tags:
    - cis-level-2
    - cis_4.2
    - cis_4.2.3
- name: CIS 4.2.4 Log Suspicious Packets (net.ipv4.conf.all.log_martians)
  sysctl: >
    name=net.ipv4.conf.all.log_martians
    value=1
    state=present
    ignoreerrors=yes
    sysctl_file=/etc/sysctl.conf
  tags:
    - cis-level-1
    - cis_4.2
    - cis_4.2.4
- name: CIS 4.2.4 Log Suspicious Packets (net.ipv4.conf.default.log_martians)
  sysctl: >
    name=net.ipv4.conf.default.log_martians
    value=1
    state=present
    ignoreerrors=yes
    sysctl_file=/etc/sysctl.conf
  tags:
    - cis-level-1
    - cis_4.2
    - cis_4.2.4
- name: CIS 4.2.5 Enable Ignore Broadcast Requests
  sysctl: >
    name=net.ipv4.icmp_echo_ignore_broadcasts
    value=1
    state=present
    ignoreerrors=yes
    sysctl_file=/etc/sysctl.conf
  tags:
    - cis-level-1
    - cis_4.2
    - cis_4.2.5
- name: CIS 4.2.6 Enable Bad Error Message Protection
  sysctl: >
    name=net.ipv4.icmp_ignore_bogus_error_responses
    value=1
    state=present
    ignoreerrors=yes
    sysctl_file=/etc/sysctl.conf
  tags:
    - cis-level-1
    - cis_4.2
    - cis_4.2.6
- name: CIS 4.2.7 Enable RFC-recommended Source Route Validation (net.ipv4.conf.all.rp_filter)
  sysctl: >
    name=net.ipv4.conf.all.rp_filter
    value=1
    state=present
    ignoreerrors=yes
    sysctl_file=/etc/sysctl.conf
  tags:
    - cis-level-2
    - cis_4.2
    - cis_4.2.7
- name: CIS 4.2.7 Enable RFC-recommended Source Route Validation (net.ipv4.conf.default.rp_filter)
  sysctl: >
    name=net.ipv4.conf.default.rp_filter
    value=1
    state=present
    ignoreerrors=yes
    sysctl_file=/etc/sysctl.conf
  tags:
    - cis-level-2
    - cis_4.2
    - cis_4.2.7
- name: CIS 4.2.8 Enable TCP SYN Cookies
  sysctl: >
    name=net.ipv4.tcp_syncookies
    value=1
    state=present
    ignoreerrors=yes
    sysctl_file=/etc/sysctl.conf
  tags:
    - cis-level-1
    - cis_4.2
    - cis_4.2.8
