## CIS 4.5 Install TCP Wrappers
- name: CIS 4.5.1 Install TCP Wrappers
  yum: >
    name=tcp_wrappers
    state=present
  tags:
    - cis-level-1
    - cis-sec_4.5
    - cis-sec_4.5.1

- name: 4.5.2 Create /etc/hosts.allow (Not Scored)
  lineinfile: >
    state=present
    create=yes
    dest=/etc/hosts.allow
    regexp=^ALL
    line=ALL:{{ tcp_allow | default("ALL") }}
  tags:
    - notscored
    - section4.5
    - section4.5.2
- name: 4.5.3 Verify Permissions on /etc/hosts.allow (Scored)
  file: >
    path=/etc/hosts.allow
    mode=0644
  tags:
    - scored
    - section4.5
    - section4.5.3

# CIS 4.5.2 Create /etc/hosts.allow
### - cis-level-1

# CIS 4.5.3 Verify Permissions on /etc/hosts.allow
### - cis-level-1
chmod 644 /etc/hosts.allow
chown root:root /etc/hosts.allow

# CIS 4.5.4 Create /etc/hosts.deny
### - cis-level-1
echo "ALL: ALL" >> /etc/hosts.deny

# CIS 4.5.5 Verify Permissions on /etc/hosts.deny 
### - cis-level-1
chmod 644 /etc/hosts.deny
chown root:root /etc/hosts.deny
